import pandas as pd
import app_components as ui

# Constantes e Nome de Arquivos ---------------------------------------------
ANO = 2018
# EMIT para Recursos, DEST para Usos
TIPO = 'DEST'
NFE = f'./data/pib_{int(ANO)}_NFe.csv'
NCM_MERGED = './data/NCM_MERGED_LEFT.csv'
CNAE_MERGED = f'./data/SCN_CNAE_{TIPO}.csv'

# Dicionários e Listas ------------------------------------------------------
tipo_bec = {
    # 'BENS INTERMEDIARIOS' : ['111','121','21','22','31','322','42','53'],
    'TODOS' : ['0','41','521','111','121','21','22','31','322','42','53','61'
    '51','522','62','63','112','122','321','7'],
}
produtos_ex_servicos = [
    "ARROZ; TRIGO E OUTROS CEREAIS",
    "CANA-DE-ACUCAR",
    "OUTROS PRODUTOS E SERVICOS DA LAVOURA TEMPORARIA",
    "LARANJA",
    "PRODUTOS DA LAVOURA PERMANENTE",
    "BOVINOS E OUTROS ANIMAIS VIVOS; PRODS. ANIMAL; CACA E SERV.",
    "LEITE DE VACA E DE OUTROS ANIMAIS",
    "SUINOS",
    "AVES E OVOS",
    "PRODUTOS DA EXPLORACAO FLORESTAL E DA SILVICULTURA",
    "PESCA E AQUICULTURA (PEIXE; CRUSTACEOS E MOLUSCOS)",
    "PETROLEO; GAS NATURAL E SERVICOS DE APOIO",
    "OUTROS PRODUTOS DA INDUSTRIA EXTRATIVA",
    "LEITE E OUTRO PRODUTOS DO LATICINIO",
    "ACUCAR",
    "OUTRO PRODUTOS ALIMENTICIOS",
    "BEBIDAS",
    "PRODUTOS DO FUMO",
    "PRODUTOS TEXTEIS",
    "ARTIGOS DO VESTUARIO E ACESSORIOS",
    "CALCADOS E ARTEFATOS DE COURO",
    "PRODUTOS DE MADEIRA; EXCLUSIVE MOVEIS",
    "CELULOSE; PAPEL; PAPELAO; EMBALAGENS E ARTEFATOS DE PAPEL",
    "SERVICOS DE IMPRESSAO E REPRODUCAO",
    "PRODUTOS DO REFINO DO PETROLEO; ETANOL E OUTROS BIOCOMBUSTIVEIS",
    "PRODUTOS QUIMICOS ORGANICOS E INORGANICOS; RESINA; ELASTOMERO E FIBRAS ARTIF. E SINTETICAS",
    "PERFUMARIA; SABOES E ARTIGOS DE LIMPEZA",
    "PRODUTOS QUIMICOS DIVERSOS",
    "PRODUTOS FARMACEUTICOS",
    "ARTIGOS DE BORRACHA E PLASTICO",
    "CIMENTO",
    "OUTROS PRODUTOS DE MINERAIS NAO METALICOS",
    "PRODUTOS DA METALURGIA",
    "PRODUTOS DE METAL; EXCL. MAQUINAS E EQUIPAMENTOS",
    "EQUIPAMENTOS DE INFORMATICA; PRODUTOS ELETRONICOS E OPTICOS",
    "MAQUINAS; APARELHOS E MATERIAIS ELETRICOS",
    "MAQUINAS E EQUIPAMENTOS",
    "AUTOMOVEIS; CAMINHOES; ONIBUS; CARROCERIAS E REBOQUES",
    "PECAS; ACESSORIOS PARA VEICULOS AUTOMOTORES E OUTROS EQUIPAMENTOS DE TRANSPORTE",
    "MOVEIS",
    "PRODUTOS DE INDUSTRIAS DIVERSAS",
]
setores = [
    "AGRICULTURA",
    "PECUARIA",
    "PRODUCAO FLORESTAL; PESCA E AQUICULTURA",
    "EXTRACAO DE PETROLEO E GAS",
    "OUTROS DA INDUSTRIA EXTRATIVA",
    "ALIMENTOS",
    "BEBIDAS E FUMO",
    "TEXTEIS E VESTUARIO",
    "CALCADOS E ARTEFATOS DE COURO",
    "PRODUTOS DE MADEIRA; CELULOSE; PAPEL; IMPRESSAO E GRAVACAO",
    "REFINO DE PETROLEO E BIOCOMBUSTIVEIS",
    "QUIMICOS; BORRACHA E PLASTICO",
    "CIMENTO",
    "OUTROS MINERAIS NAO METALICOS E SIDERURGIA",
    "MAQUINAS; EQUIPAMENTOS E MANUTENCAO",
    "AUTOMOVEIS; PECAS E ACESSORIOS",
    "MOVEIS E PRODUTOS DE INDUSTRIAS DIVERSAS",
    "ENERGIA ELETRICA; GAS NATURAL E OUTRAS UTILIDADES",
    "AGUA; ESGOTO E GESTAO DE RESIDUOS",
    "CONSTRUCAO",
    "COMERCIO",
    "TRANSPORTE TERRESTRE",
    "TRANSPORTE AQUAVIARIO",
    "TRANSPORTE AEREO",
    "ARMAZENAMENTO; ATIVIDADES AUXILIARES DOS TRANSPORTES E CORREIO",
    "ALOJAMENTO",
    "ALIMENTACAO",
    "SERVICOS DE INFORMACAO",
    "INTERMEDIACAO FINANCEIRA",
    "ATIVIDADES IMOBILIARIAS",
    "SERVICOS AS IMPRESAS",
    "ALUGUEIS NAO-IMOBILIARIOS E OUTRAS ATIVIDADES ADMINISTRATIVAS",
    "SAUDE PUBLICA; EDUCACAO PUBLICA E ADMINISTRACAO PUBLICA",
    "EDUCACAO PRIVADA",
    "SAUDE PRIVADA",
    "SERVICOS AS FAMILIAS"
]
todos_produtos_scn = [
    "ARROZ; TRIGO E OUTROS CEREAIS",
    "CANA-DE-ACUCAR",
    "OUTROS PRODUTOS E SERVICOS DA LAVOURA TEMPORARIA",
    "LARANJA",
    "PRODUTOS DA LAVOURA PERMANENTE",
    "BOVINOS E OUTROS ANIMAIS VIVOS; PRODS. ANIMAL; CACA E SERV.",
    "LEITE DE VACA E DE OUTROS ANIMAIS",
    "SUINOS",
    "AVES E OVOS",
    "PRODUTOS DA EXPLORACAO FLORESTAL E DA SILVICULTURA",
    "PESCA E AQUICULTURA (PEIXE; CRUSTACEOS E MOLUSCOS)",
    "PETROLEO; GAS NATURAL E SERVICOS DE APOIO",
    "OUTROS PRODUTOS DA INDUSTRIA EXTRATIVA",
    "LEITE E OUTRO PRODUTOS DO LATICINIO",
    "ACUCAR",
    "OUTRO PRODUTOS ALIMENTICIOS",
    "BEBIDAS",
    "PRODUTOS DO FUMO",
    "PRODUTOS TEXTEIS",
    "ARTIGOS DO VESTUARIO E ACESSORIOS",
    "CALCADOS E ARTEFATOS DE COURO",
    "PRODUTOS DE MADEIRA; EXCLUSIVE MOVEIS",
    "CELULOSE; PAPEL; PAPELAO; EMBALAGENS E ARTEFATOS DE PAPEL",
    "SERVICOS DE IMPRESSAO E REPRODUCAO",
    "PRODUTOS DO REFINO DO PETROLEO; ETANOL E OUTROS BIOCOMBUSTIVEIS",
    "PRODUTOS QUIMICOS ORGANICOS E INORGANICOS; RESINA; ELASTOMERO E FIBRAS ARTIF. E SINTETICAS",
    "PERFUMARIA; SABOES E ARTIGOS DE LIMPEZA",
    "PRODUTOS QUIMICOS DIVERSOS",
    "PRODUTOS FARMACEUTICOS",
    "ARTIGOS DE BORRACHA E PLASTICO",
    "CIMENTO",
    "OUTROS PRODUTOS DE MINERAIS NAO METALICOS",
    "PRODUTOS DA METALURGIA",
    "PRODUTOS DE METAL; EXCL. MAQUINAS E EQUIPAMENTOS",
    "EQUIPAMENTOS DE INFORMATICA; PRODUTOS ELETRONICOS E OPTICOS",
    "MAQUINAS; APARELHOS E MATERIAIS ELETRICOS",
    "MAQUINAS E EQUIPAMENTOS",
    "AUTOMOVEIS; CAMINHOES; ONIBUS; CARROCERIAS E REBOQUES",
    "PECAS; ACESSORIOS PARA VEICULOS AUTOMOTORES E OUTROS EQUIPAMENTOS DE TRANSPORTE",
    "MOVEIS",
    "PRODUTOS DE INDUSTRIAS DIVERSAS",
    "MANUTENCAO; REPARACAO E INSTALACAO DE MAQUINAS E EQUIPAMENTOS",
    "ELETRICIDADE; GAS E OUTRAS UTILIDADES",
    "AGUA; ESGOTO; RECICLAGEM E GESTAO DE RESIDUOS",
    "EDIFICACOES",
    "OBRAS DE INFRA-ESTRUTURA",
    "SERVICOS ESPECIALIZADOS PARA CONSTRUCAO",
    "COMERCIO E REPARACAO DE VEICULOS",
    "COMERCIO POR ATACADO E A VAREJO; EXCETO VEICULOS AUTOMOTORES",
    "TRANSPORTE TERRESTRE DE CARGA",
    "TRANSPORTE RODOVIARIO DE PASSAGEIROS",
    "TRANSPORTE AQUAVIARIO",
    "TRANSPORTE AEREO",
    "ARMAZENAMENTO E SERVICOS AUXILIARES AOS TRANSPORTES",
    "CORREIO E OUTROS SERVICOS DE ENTREGA",
    "SERVICOS DE ALOJAMENTO EM HOTEIS E SIMILARES",
    "SERVICOS DE ALIMENTACAO",
    "LIVROS; JORNAIS E REVISTAS",
    "SERVICOS CINEMATOGRAFICOS; MUSICA; RADIO E TELEVISAO",
    "SERVICOS DE TELECOMUNICACOES",
    "TELECOMUNICACOES; TV POR ASSINATURA; DESENVOLVIMENTO DE SISTEMAS E OUTROS SERVICOS DE INFORMACAO",
    "INTERMEDIACAO FINANCEIRA; SEGUROS E PREVIDENCIA COMPLEMENTAR",
    "ALUGUEL EFETIVO E SERVICOS IMOBILIARIOS",
    "ATIVIDADES PROFISSIONAIS; CIENTIFICAS E TECNICAS",
    "ATIVIDADES ADMINISTRATIVAS E SERVICOS COMPLEMENTARES",
    "SERVICOS COLETIVOS DA ADMINISTRACAO PUBLICA E SEGURIDADE SOCIAL",
    "EDUCACAO PUBLICA",
    "EDUCACAO PRIVADA",
    "SAUDE PUBLICA",
    "SAUDE PRIVADA",
    "SERVICOS DE ARTES; CULTURA; ESPORTE E RECREACAO",
    "ORGANIZACOES PATRONAIS; SINDICAIS E OUTROS SERVICOS ASSOCIATIVOS",
    "MANUTENCAO DE COMPUTADORES; TELEFONES E OBJETOS DOMESTICOS",
    "SERVICOS PESSOAIS",
    "SERVICOS DOMESTICOS",
]

# Dataframes em Uso ---------------------------------------------------------
nota = pd.read_csv(NFE,delimiter=';',encoding='ISO-8859-1',dtype={'NCM':str})
ncm_merg = pd.read_csv(NCM_MERGED,dtype={'NCM':str})
scn_cnae = pd.read_csv(CNAE_MERGED, dtype={f'CNAE_{TIPO}':str})
df = nota.copy()

# Tratamentos e Filtros -----------------------------------------------------
df['NCM'] = ui.normalizar_ncm(df['NCM'])
ncm_merg['NCM'] = ui.normalizar_ncm(ncm_merg['NCM'])
df[f'CNAE_{TIPO}'] = ui.normalizar_cnae(df[f'CNAE_{TIPO}'])
scn_cnae[f'CNAE_{TIPO}'] = ui.normalizar_cnae(scn_cnae[f'CNAE_{TIPO}'])
scn_cnae['SETORES SCN'] = scn_cnae['SETORES SCN'].str.strip()

# Merge entre Planilhas
df = pd.merge(df, ncm_merg, on='NCM', how='left')
df = pd.merge(df, scn_cnae, on=f'CNAE_{TIPO}', how='left')

# Filtro de Dados + Precauções
df.loc[df['NCM'].str.len() < 7, 'NCM'] = ('NA')
df = df[df['UF_EMIT'] == 'SE']
df = df[df['UF_DEST'] == 'SE']
codigos_filtrar = tipo_bec['TODOS']
df = df[df['BEC'].isin(codigos_filtrar)]
df.columns = df.columns.str.strip()
scn_cnae.columns = scn_cnae.columns.str.strip()
df = df.fillna('NA')

# Normalização da coluna Vprod e Produtos
ui.normalizar_vprod(df)
scn_norm = [i.strip().upper() for i in todos_produtos_scn]

df_agg = (
    df.groupby(['PRODUTOS SCN', 'SETORES SCN'], as_index=False)['VPROD'].sum()
)

# Construção da tabela final ------------------------------------------------
df_final = pd.DataFrame()
for setor in setores:
    lista_lin = []
    for produto in produtos_ex_servicos:
        valor = df_agg.loc[
            (df_agg['SETORES SCN'] == setor) & (df_agg['PRODUTOS SCN'] == produto),
            'VPROD'].sum()
        lista_lin.append(str(valor).replace('.', ','))
    
    dict_temp = pd.DataFrame({f"{setor}" : lista_lin})
    df_final = pd.concat([df_final, dict_temp], axis=1)

# Salvar em Excel -----------------------------------------------------------
df_final.index = produtos_ex_servicos
df_final.to_excel(f"{ANO}_{TIPO}.xlsx")